// This file is auto-generated by drizzle-kit.
// Once DATABASE_URL is set in .env.local, run:
//   npm run db:pull
// drizzle-kit will introspect your GCP Cloud SQL database and
// replace this file with your full table definitions.

export {};
